<#
.SYNOPSIS
    Configure-ShellProfiles.ps1 - Create PowerShell and Bash profiles
#>
$ErrorActionPreference = "Stop"
$cfg = $env:DEPLOY_CONFIG | ConvertFrom-Json

Write-Host "  Creating Shell Profiles..." -ForegroundColor Gray

# ============================================================================
# POWERSHELL PROFILE
# ============================================================================

$psProfileContent = @'
# ============================================================================
# PowerShell Profile - Generated by deployment script
# ============================================================================

# Aliases
Set-Alias -Name g -Value git
Set-Alias -Name d -Value docker
Set-Alias -Name c -Value code
Set-Alias -Name cc -Value claude
Set-Alias -Name cop -Value copilot

# Functions
function which { Get-Command $args[0] -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source }
function touch { param([string]$Path) if (!(Test-Path $Path)) { New-Item -ItemType File -Path $Path | Out-Null } }
function ll { Get-ChildItem -Force @args }
function mkcd { param([string]$Path) New-Item -ItemType Directory -Path $Path -Force | Out-Null; Set-Location $Path }

# Git shortcuts
function gs { git status @args }
function ga { git add @args }
function gc { git commit -m @args }
function gp { git push @args }
function gl { git pull @args }
function gd { git diff @args }
function gco { git checkout @args }
function glog { git log --oneline --graph --decorate -20 @args }

# Docker shortcuts
function dps { docker ps @args }
function di { docker images @args }

# Environment - ensure Node.js and npm-global are in PATH
$env:EDITOR = "code --wait"
$nodePath = "C:\Program Files\nodejs"
$npmGlobal = Join-Path $env:USERPROFILE ".npm-global"
$localBin = Join-Path $env:USERPROFILE ".local\bin"
if ($env:Path -notlike "*nodejs*") { $env:Path = "$nodePath;$env:Path" }
if ($env:Path -notlike "*$npmGlobal*") { $env:Path = "$npmGlobal;$env:Path" }
if ($env:Path -notlike "*$localBin*") { $env:Path = "$localBin;$env:Path" }

# Simple prompt (Oh-My-Posh will override if installed)
function prompt {
    $location = Get-Location
    $branch = ""
    if (Test-Path .git) {
        $branch = git branch --show-current 2>$null
        if ($branch) { $branch = " ($branch)" }
    }
    "PS $location$branch> "
}

# Oh-My-Posh (if installed)
if (Get-Command oh-my-posh -ErrorAction SilentlyContinue) {
    $themePath = Join-Path $env:USERPROFILE ".config\oh-my-posh\themes\devenv.omp.json"
    if (Test-Path $themePath) {
        oh-my-posh init pwsh --config $themePath | Invoke-Expression
    } else {
        oh-my-posh init pwsh | Invoke-Expression
    }
}
'@

# Use Downloads\WindowsPowerShell to avoid OneDrive sync issues
$customProfileDir = Join-Path $env:USERPROFILE "Downloads\WindowsPowerShell"
$customProfile = Join-Path $customProfileDir "Microsoft.PowerShell_profile.ps1"

if (!(Test-Path $customProfileDir)) {
    New-Item -ItemType Directory -Path $customProfileDir -Force | Out-Null
}
$psProfileContent | Set-Content -Path $customProfile -Encoding UTF8
Write-Host "    PowerShell profile: $customProfile" -ForegroundColor DarkGray

# Add loader to system-wide profile to source from Downloads
$systemProfile = "C:\Windows\System32\WindowsPowerShell\v1.0\profile.ps1"
$loaderContent = @"

# Load user profile from Downloads (bypass OneDrive)
`$customProfile = Join-Path `$env:USERPROFILE "Downloads\WindowsPowerShell\Microsoft.PowerShell_profile.ps1"
if (Test-Path `$customProfile) {
    . `$customProfile
}
"@

$existingContent = ""
if (Test-Path $systemProfile) {
    $existingContent = Get-Content $systemProfile -Raw -ErrorAction SilentlyContinue
}
if ($existingContent -notlike "*Downloads\WindowsPowerShell*") {
    Add-Content -Path $systemProfile -Value $loaderContent
    Write-Host "    System profile loader added" -ForegroundColor DarkGray
}

# Also write to PowerShell 7 profile location
$ps7Profile = Join-Path $env:USERPROFILE "Documents\PowerShell\Microsoft.PowerShell_profile.ps1"
$ps7ProfileDir = Split-Path $ps7Profile -Parent
if (!(Test-Path $ps7ProfileDir)) {
    New-Item -ItemType Directory -Path $ps7ProfileDir -Force | Out-Null
}
$psProfileContent | Set-Content -Path $ps7Profile -Encoding UTF8
Write-Host "    PowerShell 7 profile: $ps7Profile" -ForegroundColor DarkGray

# ============================================================================
# WSL BASH PROFILE
# ============================================================================

$bashProfile = @'
# Bash Profile Additions - Generated by deployment script
# Source from .bashrc: source ~/.profile_additions

export PATH="$HOME/.local/bin:$HOME/.npm-global/bin:$PATH"
export EDITOR="code --wait"
export VISUAL="code --wait"
export DOCKER_BUILDKIT=1
export NODE_OPTIONS="--max-old-space-size=4096"
export npm_config_prefix="$HOME/.npm-global"
export PYTHONDONTWRITEBYTECODE=1
export LANG="en_US.UTF-8"
export GPG_TTY=$(tty)

# Aliases
alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git pull'
alias glog='git log --oneline --graph --decorate -20'
alias d='docker'
alias dc='docker compose'
alias dps='docker ps'
alias ll='ls -alF --color=auto'
alias la='ls -A --color=auto'
alias ..='cd ..'
alias c='code'
alias cc='claude'
alias cop='copilot'

# Prompt with Git branch
parse_git_branch() { git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'; }
export PS1="\[\033[32m\]\u@\h\[\033[00m\]:\[\033[34m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\]\$ "
'@

# Save bash profile for WSL
$bashProfilePath = Join-Path $PSScriptRoot "..\..\docs\bash_profile_additions.sh"
$bashProfile.Replace("`r`n", "`n") | Set-Content -Path $bashProfilePath -Encoding UTF8 -NoNewline
Write-Host "    Bash profile template: docs\bash_profile_additions.sh" -ForegroundColor DarkGray

# Apply to WSL if available
Write-Host "  Applying Bash profile to WSL..." -ForegroundColor Gray
try {
    # Use unique temp file to avoid race conditions
    $guid = [System.Guid]::NewGuid().ToString("N")
    $tempFile = Join-Path $env:TEMP "profile_additions_$guid.sh"
    $bashProfile.Replace("`r`n", "`n") | Set-Content -Path $tempFile -Encoding UTF8 -NoNewline

    # Quote the path properly for wslpath
    $windowsPath = $tempFile.Replace('\', '/')
    $wslTempPath = wsl wslpath -u "$windowsPath" 2>$null
    if ($wslTempPath) {
        # Use escaped path in bash command
        $escapedPath = $wslTempPath.Replace("'", "'\\''")
        wsl -d Ubuntu bash -c "cp '$escapedPath' ~/.profile_additions && grep -q 'profile_additions' ~/.bashrc 2>/dev/null || echo 'source ~/.profile_additions' >> ~/.bashrc" 2>$null
        Write-Host "    Applied to WSL Ubuntu" -ForegroundColor DarkGray
    }

    # Small delay to ensure WSL command completes before cleanup
    Start-Sleep -Milliseconds 100
    Remove-Item $tempFile -Force -ErrorAction SilentlyContinue
} catch {
    Write-Host "    WSL profile will apply on first login" -ForegroundColor Yellow
}

Write-Host "  Shell profiles created" -ForegroundColor Green
exit 0
