<#
.SYNOPSIS
    Configure-WSL.ps1 - Configure WSL2 with mirrored networking mode
#>
$ErrorActionPreference = "Stop"
$cfg = $env:DEPLOY_CONFIG | ConvertFrom-Json

$wslConfigPath = Join-Path $env:USERPROFILE ".wslconfig"

Write-Host "  Creating WSL2 configuration..." -ForegroundColor Gray

$memory = "$($cfg.resources.wsl_memory_gb)GB"
$processors = $cfg.resources.wsl_processors
$swap = "$($cfg.resources.wsl_swap_gb)GB"

$wslConfig = @"
# WSL2 Configuration - Generated by deployment script
# Mirrored networking enabled for seamless localhost access

[wsl2]
# Network Configuration - Mirrored Mode
networkingMode=mirrored
dnsTunneling=true
autoProxy=true
hostAddressLoopback=true

# Resource Allocation
memory=$memory
processors=$processors
swap=$swap

# Features
localhostForwarding=true
nestedVirtualization=true
guiApplications=true

# Debugging
debugConsole=false

[experimental]
# Memory optimization
autoMemoryReclaim=gradual
sparseVhd=true
"@

# Backup existing config
if (Test-Path $wslConfigPath) {
    $backup = "$wslConfigPath.backup.$(Get-Date -Format 'yyyyMMddHHmmss')"
    Copy-Item $wslConfigPath $backup
    Write-Host "    Backed up existing config to: $backup" -ForegroundColor DarkGray
}

# Write new config
$wslConfig | Set-Content -Path $wslConfigPath -Encoding UTF8

Write-Host "    .wslconfig created:" -ForegroundColor Green
Write-Host "      Memory: $memory" -ForegroundColor DarkGray
Write-Host "      Processors: $processors" -ForegroundColor DarkGray
Write-Host "      Networking: mirrored" -ForegroundColor DarkGray
Write-Host "      DNS Tunneling: enabled" -ForegroundColor DarkGray

# Shutdown WSL to apply changes
Write-Host "  Restarting WSL to apply configuration..." -ForegroundColor Gray
wsl --shutdown 2>$null
Start-Sleep -Seconds 2

Write-Host "  WSL2 configured with mirrored networking" -ForegroundColor Green
exit 0
