# Bash Profile Additions - Generated by deployment script
# Source from .bashrc: source ~/.profile_additions

export PATH="$HOME/.local/bin:$HOME/.npm-global/bin:$PATH"
export EDITOR="code --wait"
export VISUAL="code --wait"
export DOCKER_BUILDKIT=1
export NODE_OPTIONS="--max-old-space-size=4096"
export npm_config_prefix="$HOME/.npm-global"
export PYTHONDONTWRITEBYTECODE=1
export LANG="en_US.UTF-8"
export GPG_TTY=$(tty)

# Aliases
alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git pull'
alias glog='git log --oneline --graph --decorate -20'
alias d='docker'
alias dc='docker compose'
alias dps='docker ps'
alias ll='ls -alF --color=auto'
alias la='ls -A --color=auto'
alias ..='cd ..'
alias c='code'
alias cc='claude'
alias cop='copilot'

# Prompt with Git branch
parse_git_branch() { git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'; }
export PS1="\[\033[32m\]\u@\h\[\033[00m\]:\[\033[34m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\]\$ "